spring.application.name=aduana-api
server.port=8080

# --- Conexión Oracle Cloud (vía Wallet) ---

#Si quieres usar su BD Cambiar esto------------
spring.datasource.url=jdbc:oracle:thin:@clases_high?TNS_ADMIN=X:/Analista/Proyectos/SistemaAduana/Wallet_clases
spring.datasource.username=ADMIN
spring.datasource.password=Computador2324.
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#-----------------------------------------------------

# --- Configuración JPA/Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Ejecución de scripts SQL ---
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true